### ISSUE TITLE
launchdarkly-server-sdk.c won't compile with LuaJIT

### ISSUE THREAD

**Issue by LeshnaShamloll** [launchdarkly/lua-server-sdk#14]
When using luarocks provided by LuaJIT (version 2.1) to make the launchdarkly-server-sdk-1.0-0.rockspec file, the launchdarkly-server-sdk.c file (from release version 1.0.0) fails to compile, with an error saying:

```
launchdarkly-server-sdk.c:1179:13: error: static declaration of 'luaL_setfuncs' follows non-static declaration
 1179 | static void luaL_setfuncs (lua_State *L, const luaL_Reg *l, int nup) {
      |             ^~~~~~~~~~~~~
In file included from launchdarkly-server-sdk.c:7:
/usr/local/openresty/luajit/include/luajit-2.1/lauxlib.h:88:18: note: previous declaration of 'luaL_setfuncs' was here
   88 | LUALIB_API void (luaL_setfuncs) (lua_State *L, const luaL_Reg *l, int nup);
      |                  ^~~~~~~~~~~~~

Error: Build error: Failed compiling object launchdarkly-server-sdk.o
launchdarkly-server-sdk 1.0-0 depends on lua >= 5.1, <= 5.4 (5.1-1 provided by VM)
gcc -O2 -fPIC -I/usr/local/openresty/luajit/include/luajit-2.1 -c launchdarkly-server-sdk.c -o launchdarkly-server-sdk.o -I/usr/local/include
```

This is probably because the preprocessor directive at line 1175
`#if !defined LUA_VERSION_NUM || LUA_VERSION_NUM==501`
adds a `luaL_setfuncs` function since Lua5.1 doesn't seem to have it, but this method is already present in LuaJIT, resulting in a conflict.

Since the Readme mentions support for LuaJIT, we assume that this is an issue.

**Comment by hroederld** [comment]
Hello @LeshnaShamloll 

After looking around for similar issues this appears to specifically be an issue with compatibility with the beta version of LuaJIT. We test against stable releases for Lua 5.3, 5.2, and LuaJIT in CI, and are fairly confident it is compatible in the general case.

We will look at updating the SDK to support LuaJIT-2.1.0-beta3 and hopefully get a new release out soon. If you need to use the SDK immediately consider using a stable LuaJIT version, or manually deleting the SDKs redefinition of `luaL_setfuncs`.

**Comment by LeshnaShamloll** [comment]
Great, thank you. :)

**Comment by hroederld** [comment]
Hi @LeshnaShamloll we recently pushed a new release that should mitigate this issue.

Let us know if you have any more problems. Thanks!

**Comment by LeshnaShamloll** [comment]
Thank you :)
