### ISSUE TITLE
Lua SDK potentially unsafe to use within openresty/nginx

### ISSUE THREAD

**Issue by tyree731** [launchdarkly/lua-server-sdk#6]
I've been looking around the lua-server-sdk with some interest, as I use Kong at the company I work for (FactSet Research Systems). One thing that jumped out at me as a potential issue is that the [Lua library](https://github.com/launchdarkly/lua-server-sdk/blob/master/launchdarkly-server-sdk.lua) is a shim to the C SDK. A note from the [openresty documentation](https://openresty-reference.readthedocs.io/en/latest/Lua_Nginx_API/) you link to in the nginx example says:

> Network I/O operations in user code should only be done through the Nginx Lua API calls as the Nginx event loop may be blocked and performance drop off dramatically otherwise.

Essentially, openresty provides a [set of socket primitives](https://openresty-reference.readthedocs.io/en/latest/Lua_Nginx_API/#ngxsockettcp) that integrate with the nginx/openresty event loop in a nonblocking fashion, and if you aren't using them directly, then any network operations performed by your SDK will block the event loop, limiting the usability of the SDK.

Since it seems like openresty is one of the use cases you guys are targeting, I figured this was worth raising as an issue. Thanks!

**Comment by hroederld** [comment]
Hi @tyree731 thanks for your issue!

There are not actually any operations that block the worker on any network action. Evaluating flags is done against a previously downloaded ruleset, sending events puts them on a queue, etc. The network actions are implemented as one background thread multiplexing a few different operations.

I agree that blocking the NGINX worker directly would be absolutely horrible for performance, however if that is done in another thread that only does background tasks the only inefficiency comes from the minor overhead of thread context switching.

**Comment by tyree731** [comment]
Thanks for the clarification! Closing this
